#!/bin/bash

# define the exit codes
SUCCESS=0
ERR_NOINPUT=1
ERR_NOPARAMS=2
ERR_GDAL=4
ERR_COPY=5

# add a trap to exit gracefully
function cleanExit ()
{
   local retval=$?
   local msg=""
   case "$retval" in
     $SUCCESS)      msg="Processing successfully concluded";;
     $ERR_NOPARAMS) msg="Outout format not defined";;
     $ERR_GDAL)     msg="Graph processing of job ${JOBNAME} failed (exit code $res)";;
     *)             msg="Unknown error";;
   esac
   [ "$retval" != "0" ] && logerror "Error $retval - $msg, processing aborted" || loginfo "$msg"
   exit $retval
}
trap cleanExit EXIT

case "$USER" in
    mapred )
        # source the ciop functions (e.g. ciop-log)
        # The file is /usr/lib/ciop/libexec/ciop-functions.sh
        source ${ciop_job_include}
        BINDIR=/application/growingseason/bin
        function loginfo () { ciop-log INFO "$@"; }
        function logerror () { ciop-log ERROR "$@"; }
        function copy () {
            url="$1"
            dst="$2"
            loginfo "Copying <$url> to <$dst>"
            ciop-copy -r 3 -f -O $dst $url
        }
        ;;
    * )
        # create aliases for ciop routines
        TMPDIR=${TMPDIR-.}
        BINDIR=./bin/
        # function ciop-log { echo -- CIOP-LOG "$@"; }
        function loginfo () { echo "INFO: $@"; }
        function logerror () { echo " ERROR: $@"; }
        function ciop-publish { echo -- CIOP-PUBLISH "$@"; }
        copy () {
            url="$1"
            dst="$2"
            loginfo "Copying (linking) <$url> to <$dst>"
            ln -s "$url" "$dst/."
        }

        _tilesize=${6-1024}
        function ciop-getparam { echo $(eval echo '$'"_$1"); }
        ;;
esac

interp=/usr/bin/python
script=${BINDIR}/sensyf-tile


tilesize=$(ciop-getparam tilesize)
loginfo "tilesize: $tilesize"

FLAGS="-r $tilesize -organize_by_tile "

# create the input directory
SRCDIR=$TMPDIR/inputs/
mkdir -p $SRCDIR
rm -rf $SRCDIR/*
# DSTDIR=$TMPDIR/tile_files/
DSTDIR="$TMPDIR/${mapred_task_id-$(date '+%FT%H%M%S')-$$}"
mkdir -p $DSTDIR
rm -rf $DSTDIR/*

copy_inputs () {
    while read -r url; do
         copy $url $SRCDIR || exit $ERR_COPY
    done
}

# mode=$(ciop-getparam mode)


loginfo "*** running tiling ***"

copy_inputs

# python toy_tile.py srcdir dstdir
loginfo 'tiling  ...'
echo $interp $script $FLAGS $SRCDIR $DSTDIR
$interp $script $FLAGS $SRCDIR $DSTDIR                 # > /dev/null 2>&1

# Create one tar file per tile, containing all inputs for that tile

cd $DSTDIR
for tile in *; do
    tar zcvf $tile.tar.gz $tile
    rm -rf $tile
done


ciop-publish -r $DSTDIR

exit 0
